name: ci.pr # Name of action

on: # Event to trigger the the action
  pull_request:
    branches:
      - main # Will trigger when having a push action to a MR to main branch
    paths-ignore: # Will not trigger if the push only include one of below things
      - '**.md'
      - '.vscode/**'

jobs: # jobs need to be run
  build:
    runs-on: ubuntu-latest # environment want to be used to run, we can use container or docker also
    steps:
      - uses: actions/checkout@v3 # checkout get the code
      - name: node # name of step
        uses: actions/setup-node@v1 # setup node
        with:
          node-version: 12.x # version 12.x
      - name: 'install:linux:dep' # name of step
        run: | # execute update and install libraries
          sudo apt-get update
          sudo apt-get install libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 libhyphen0 libgdk-pixbuf2.0-0 libegl1 libgles2 libevent-dev libnotify4 libxslt1.1
          sudo apt-get install xvfb
      - name: 'npm:install' # name of step
        run: npm install # execute install packages
        env:
          CI: true
      - name: lint # name of step
        run: npm run lint --if-present
      - name: build # name of step
        run: npm run build --if-present
      - name: test # name of step
        run: npm run test